### PR TITLE
Prepare for laravel 9

### PR DESCRIPTION
**Pull request by Jubeki**
Waiting for https://github.com/BrainMaestro/composer-git-hooks/pull/124

### CODE REVIEW

**Comment by Jubeki** [comment]
@inxilpro I can make this package Laravel 9 compatible if I remove `BrainMaestro/composer-git-hooks`.
Since you already have a workflow for the style check in place you don't need to check before committing or pushing I think.

**Comment by inxilpro** [comment]
Hm. Yeah, I guess that's fine. Go for it!

**Comment by Jubeki** [comment]
Okay, I removed the dependency.
Tests passed on my repository.

**Comment by Jubeki** [comment]
I just tested my branch on a Laravel 9 Project and everything seems to be working fine.

**Comment by inxilpro** [comment]
Thanks!

**Pull request merged**
